### ISSUE TITLE
How can I generate time-sensitive music

### ISSUE THREAD

**Issue by sankexin** [salu133445/musegan#110]
How can I generate long time music？such as：3-4 minutes

**Comment by VegetaDTX** [comment]
I wonder about this too. I am very interested in how do we go about creating samples that last for 1 minute or more?

More specifically - do we need to train it with different settings in order to sample longer samples, or can we get 1 minute-long or longer samples with one of your pretrained models?

I would really appreciate an answer to this!

**Comment by salu133445** [comment]
The current model can only generate 4-measure or 8-measure music as convolutional GANs can only handle fixed-length samples.

It's possible to play with latent space to form a longer song by putting together the generated segments, but that's another thing.

**Comment by VegetaDTX** [comment]
Thank you for your answer @salu133445 !
I will try my luck with the latent space stuff.

**Comment by chessnocow** [comment]
@salu133445 How can I remove silence between samples in one file? There is one empty measure before every 4 bins sample.

**Comment by chessnocow** [comment]
> The current model can only generate 4-measure or 8-measure music as convolutional GANs can only handle fixed-length samples.

How to generate 8-measure samples? I've tried to change data_shape in params but it didn't work for me.


Traceback (most recent call last):
  File "/content/musegan/scripts/../src/train.py", line 348, in <module>
    main()
  File "/content/musegan/scripts/../src/train.py", line 184, in main
    x=train_x, mode='train', params=params, config=config)
  File "/content/musegan/src/musegan/model.py", line 60, in __call__
    return self.get_train_nodes(x, z, y, c, params, config)
  File "/content/musegan/src/musegan/model.py", line 132, in get_train_nodes
    inter_x = eps_x * x + (1.0 - eps_x) * nodes['fake_x']
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/root/.local/share/virtualenvs/content-cQIIIOO2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 8 and 4 for 'Model_1/add' (op: 'Add') with input shapes: [64,8,48,84,5], [64,4,48,84,5].

**Comment by salu133445** [comment]
To change from 4 measures to 8 measures, you also need to change the network architecture.

**Comment by salu133445** [comment]
> @salu133445 How can I remove silence between samples in one file? There is one empty measure before every 4 bins sample.

You need to modify [this line](https://github.com/salu133445/musegan/blob/3e104779cc76a008d319775321987f84ba0203c9/src/musegan/io_utils.py#L253).

**Comment by soheilKLQC** [comment]
Would someone have an example code as he applied the appropriate programs. I would like to apply this to my music but I can hardly see through it and would like to see an application.
