### ISSUE TITLE
AttributeError: 'PrefetchDataset' object has no attribute 'make_one_shot_iterator'

### ISSUE THREAD

**Issue by boobootoo2** [salu133445/musegan#115]
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/jgs/Projects/python/musegan/scripts/../src/train.py", line 348, in <module>
    main()
  File "/Users/jgs/Projects/python/musegan/scripts/../src/train.py", line 172, in main
    train_x, _ = load_training_data(params, config)
  File "/Users/jgs/Projects/python/musegan/scripts/../src/train.py", line 105, in load_training_data
    train_x, train_y = dataset.make_one_shot_iterator().get_next(), None
AttributeError: 'PrefetchDataset' object has no attribute 'make_one_shot_iterator'
(jupyter) bash-3.2$

**Comment by ruscot** [comment]
I had the same issue, to solve I replace the lane like this : 
Last code :
```
    if params['is_conditional']:
        train_x, train_y = dataset.make_one_shot_iterator().get_next()
    else:
        train_x, train_y = dataset.make_one_shot_iterator().get_next(), None
```
New code : 
```
    if params['is_conditional']:
        train_x, train_y = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    else:
        train_x, train_y = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next(), None
```

**Comment by ruscot** [comment]
But it seems to have other issue due to tensorflow update.... A refactoring seems necessary no ?
