### ISSUE TITLE
pip3 install -r requirements.txt failed with python3.10

### ISSUE THREAD

**Issue by mazhenke** [salu133445/musegan#139]
(musegan) mzk@DESKTOP-9LJNKOC:/mnt/e/Work/musegan/musegan$ pip3 install -r requirements.txt
Collecting setuptools==39.1.0
  Using cached setuptools-39.1.0-py2.py3-none-any.whl (566 kB)
Collecting absl-py==0.4.1
  Using cached absl-py-0.4.1.tar.gz (88 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-u5a2fwcu/absl-py_bada722486d343968df7b90865258df3/setup.py", line 33, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
---------------------------------------------------------------------------------------------
my python version:
3.10.9

**Comment by Qiangong2** [comment]
You need to use Python 3.8
