### ISSUE TITLE
ValueError: `pianorolls` and `program_nums` must have the samelength

### ISSUE THREAD

**Issue by AllenPeng0209** [salu133445/musegan#16]
I am trying to train lastfm_alternative_5b_phrase.npy as my dataset, and the config.py is all set to the right value. However, i got this ValueError while execute the main.py, anyone can help me ? Thanks

Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main()
  File "main.py", line 66, in main
    gan.train(x_train, CONFIG['train'])
  File "/home/allenpeng0209/musegan/musegan/musegan/models.py", line 113, in train
    self.save_samples('x_train', x_train, save_midi=True)
  File "/home/allenpeng0209/musegan/musegan/model.py", line 171, in save_samples
    midi_io.save_midi(midipath, binarized, self.config)
  File "/home/allenpeng0209/musegan/musegan/utils/midi_io.py", line 84, in save_midi
    tempo=config['tempo'])
  File "/home/allenpeng0209/musegan/musegan/utils/midi_io.py", line 36, in write_midi
    raise ValueError("`pianorolls` and `program_nums` must have the same"
ValueError: `pianorolls` and `program_nums` must have the samelength

**Comment by AllenPeng0209** [comment]
Thank you!
