### ISSUE TITLE
Why the NOT FOUND ERROR?

### ISSUE THREAD

**Issue by VickyChing** [salu133445/musegan#37]
[*] Initializing variables...
[*] Loading checkpoint...
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    main()
  File "main.py", line 62, in main
    gan.load_latest(CONFIG['exp']['pretrained_dir'])
  File "/root/chy/musegan-master/musegan/model.py", line 150, in load_latest
    checkpoint_path = tf.train.latest_checkpoint(checkpoint_dir)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1857, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 337, in get_matching_files
    for single_filename in filename
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/salu133445/NAS/salu133445/git/musegan/exp/musegan/lastfm_alternative_g_composer_d_proposed/checkpoints; No such file or directory

**Comment by salu133445** [comment]
I found that TF use absolute path to save the checkpoint paths by default. I have fixed it. It should work now (see f4811d9).

**Comment by salu133445** [comment]
We have updated the code to v3. It should now be easier to load the pretrained models. Please refer to the README file to see how to use the pretrained models.
