### ISSUE TITLE
KeyError: 'is_accompaniment'

### ISSUE THREAD

**Issue by zyoohv** [salu133445/musegan#48]
```
$ ./scripts/run_inference.sh "./exp/default/" "0"
musegan.inference    INFO     Using parameters:
{'beat_resolution': 12,
 'data_shape': [4, 48, 84, 5],
 'is_conditional': False,
 'latent_dim': 128,
 'nets': {'discriminator': 'default', 'generator': 'default'},
 'use_binary_neurons': False}
musegan.inference    INFO     Using configurations:
{'adam': {'beta1': 0.5, 'beta2': 0.9},
 'batch_size': 64,
 'checkpoint_dir': './exp/default//model',
 'colormap': [[1.0, 0.0, 0.0],
              [1.0, 0.5, 0.0],
              [0.0, 1.0, 0.0],
              [0.0, 0.0, 1.0],
              [0.0, 0.5, 1.0]],
 'columns': 5,
 'config': './exp/default//config.yaml',
 'data_filename': 'train_x_lpd_5_phr',
 'data_root': None,
 'data_source': 'sa',
 'evaluate_steps': 100,
 'gan_loss_type': 'wasserstein',
 'gpu': '0',
 'initial_learning_rate': 0.001,
 'learning_rate_schedule': {'end': 50000, 'end_value': 0.0, 'start': 45000},
 'log_loss_steps': 100,
 'lower': -2,
 'midi': {'is_drums': [1, 0, 0, 0, 0],
          'lowest_pitch': 24,
          'programs': [0, 0, 25, 33, 48],
          'tempo': 100},
 'n_dis_updates_per_gen_update': 5,
 'n_jobs': 20,
 'params': './exp/default//params.yaml',
 'result_dir': './exp/default//results/inference',
 'rows': 5,
 'runs': 10,
 'sample_grid': [8, 8],
 'save_array_samples': True,
 'save_checkpoint_steps': 10000,
 'save_image_samples': True,
 'save_pianoroll_samples': True,
 'save_samples_steps': 100,
 'save_summaries_steps': 0,
 'slope_schedule': {'end': 50000, 'end_value': 5.0, 'start': 10000},
 'steps': 50000,
 'upper': 2,
 'use_gradient_penalties': True,
 'use_learning_rate_decay': True,
 'use_random_transpose': False,
 'use_slope_annealing': False,
 'use_train_test_split': False}
musegan.model        INFO     Building model.
Traceback (most recent call last):
  File "/data00/home/zhangyonghui.98k/musegan/scripts/../src/inference.py", line 163, in <module>
    main()
  File "/data00/home/zhangyonghui.98k/musegan/scripts/../src/inference.py", line 100, in main
    model = Model(params)
  File "/data00/home/zhangyonghui.98k/musegan/src/musegan/model.py", line 37, in __init__
    if params['is_accompaniment']:
KeyError: 'is_accompaniment'
```

**Comment by salu133445** [comment]
Please add the following parameters to `params.yaml` in the experiment directory.
```yaml
is_accompaniment: false
condition_track_idx: ~
```
