### ISSUE TITLE
using single track midi 

### ISSUE THREAD

**Issue by haojiunlo** [salu133445/musegan#53]
Hi, I wonder if I can use single track midi to  train the model. Thanks.

**Comment by salu133445** [comment]
Yes. But you need to do some processing to prepare your own training data. Please refer to #51 for example code.

**Comment by haojiunlo** [comment]
Thank for answering the question. I also need to change the parameters in config.yaml and params.yaml right?

**Comment by salu133445** [comment]
Yes. You need to set the correct data shape (`data_shape`) in `params.yaml` and change the sampler settings (`midi/programs`, `midi/is_drums` and `colormap`) in `config.yaml`.

**Comment by haojiunlo** [comment]
Sorry to bother you again, I set the parameters like this 
`config.yaml`
```
midi:
  lowest_pitch: 24 # the lowest pitch of the piano-rolls
  programs: [1]
  is_drums: [0]
  tempo: 100 # in bpm
colormap:
  - [1., 0., 0.]
```
`params.yaml `
`data_shape: [4, 48, 84, 1]`

and I got this error
```
InvalidArgumentError (see above for traceback): input must be 5-dimensional
	 [[Node: Model_1/Discriminator/pitch_time_private/conv3d/Conv3D = Conv3D[T=DT_FLOAT, data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 12, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](IteratorGetNext/_1631, Model/Discriminator/pitch_time_private/conv3d/kernel/read)]]
	 [[Node: Model_1/add_3/_1637 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1224_Model_1/add_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
did I miss something or the parameter setting is wrong? Thanks.

**Comment by salu133445** [comment]
The settings are correct, so there might be a bug in the code. Can you check the shapes of the true data and the generated data? You can insert the following code right _before_ line 119 in `src/musegan/model.py` ([here](https://github.com/salu133445/musegan/blob/master/src/musegan/model.py#L119)) to check their shapes, which should both be (`batch_size`, 4, 48, 84, 1). Thanks.

```python
print("Shape of true data: ", x.get_shape())
print("Shape of fake data: ", nodes['fake_x'].get_shape())
```

**Comment by haojiunlo** [comment]
Hi, I got
```
Shape of true data:  (?, 4, 48, 84, 1)
Shape of fake data:  (64, 4, 48, 84, 1)
```

**Comment by salu133445** [comment]
Can you post the full error including the traceback? Thanks.

**Comment by haojiunlo** [comment]
Thanks for your help.

```
Traceback (most recent call last):
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input must be 5-dimensional
	 [[Node: Model_1/Discriminator/pitch_time_private/conv3d/Conv3D = Conv3D[T=DT_FLOAT, data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 12, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](IteratorGetNext/_1631, Model/Discriminator/pitch_time_private/conv3d/kernel/read)]]
	 [[Node: Model_1/add_3/_1637 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1224_Model_1/add_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hao/musegan/scripts/../src/train.py", line 349, in <module>
    main()
  File "/home/hao/musegan/scripts/../src/train.py", line 274, in main
    step = tf.train.global_step(sess, global_step)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/training_util.py", line 67, in global_step
    return int(sess.run(global_step_tensor))
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1207, in run
    run_metadata=run_metadata)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 987, in run
    return self._sess.run(*args, **kwargs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input must be 5-dimensional
	 [[Node: Model_1/Discriminator/pitch_time_private/conv3d/Conv3D = Conv3D[T=DT_FLOAT, data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 12, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](IteratorGetNext/_1631, Model/Discriminator/pitch_time_private/conv3d/kernel/read)]]
	 [[Node: Model_1/add_3/_1637 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1224_Model_1/add_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Model_1/Discriminator/pitch_time_private/conv3d/Conv3D', defined at:
  File "/home/hao/musegan/scripts/../src/train.py", line 349, in <module>
    main()
  File "/home/hao/musegan/scripts/../src/train.py", line 186, in main
    x=train_x, mode='train', params=params, config=config)
  File "/home/hao/musegan/src/musegan/model.py", line 60, in __call__
    return self.get_train_nodes(x, z, y, c, params, config)
  File "/home/hao/musegan/src/musegan/model.py", line 121, in get_train_nodes
    nodes['dis_real'] = self.dis(x, y, True)
  File "/home/hao/musegan/src/musegan/presets/discriminator/default.py", line 46, in __call__
    for _ in range(self.n_tracks)]
  File "/home/hao/musegan/src/musegan/presets/discriminator/default.py", line 46, in <listcomp>
    for _ in range(self.n_tracks)]
  File "/home/hao/musegan/src/musegan/presets/discriminator/default.py", line 17, in <lambda>
    conv_layer = lambda i, f, k, s: ACTIVATION(norm(conv3d(i, f, k, s)))
  File "/home/hao/musegan/src/musegan/presets/ops.py", line 12, in <lambda>
    i, f, k, s, kernel_initializer=CONV_KERNEL_INITIALIZER)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/layers/convolutional.py", line 630, in conv3d
    return layer.apply(inputs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/keras/layers/convolutional.py", line 186, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1361, in conv3d
    name=name)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/hao/.local/share/virtualenvs/musegan-b4wmuDEf/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): input must be 5-dimensional
	 [[Node: Model_1/Discriminator/pitch_time_private/conv3d/Conv3D = Conv3D[T=DT_FLOAT, data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 12, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](IteratorGetNext/_1631, Model/Discriminator/pitch_time_private/conv3d/kernel/read)]]
	 [[Node: Model_1/add_3/_1637 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1224_Model_1/add_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by salu133445** [comment]
This is pretty weird. It seems that the rank of tensor `x` (the true data fed to the discriminator) is wrong. But I cannot figure out where the bug is. You might want to check the actual shape of `x` at run time by replacing the line `nodes['dis_real'] = self.dis(x, y, True)` in `src/musegan/model.py` with the following code.

```python
print_op = tf.print(tf.shape(x))
with tf.control_dependencies([print_op]):
    nodes['dis_real'] = self.dis(x, y, True)
```

btw, I found an even bigger bug (though it won't cause errors) while rereading the code. :sweat_smile: 
Thanks anyway. :+1:

**Comment by haojiunlo** [comment]
It turns out that the problem is data processing.
I  add `pianoroll = pianoroll[:, np.newaxis, :, :, :]` to the example code in #51 and it works.
But I need to turn off the evaluation otherwise it returns this error
```
InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](strided_slice_1, Reshape_1/shape)]]
```
Thanks for the great work tho.:+1:

**Comment by li-car-fei** [comment]
> I checked the actual shape with following code
> 
> ```
> print_op = tf.Print(x, [tf.shape(x)], message='Debug ', summarize=5)
>             with tf.control_dependencies([print_op]):
>                 nodes['dis_real'] = self.dis(x, y, True)
> ```
> 
> and get `Debug [64 192 84 1]`
> 
> so I try to set the shape right using `.set_shape()`, but still got the same error. I'll keep trying.😅 really appreciate your help.

I meet the same problem when I train with my own data,  how can you fix this problem ?
thanks

**Comment by li-car-fei** [comment]
> This is pretty weird. It seems that the rank of tensor `x` (the true data fed to the discriminator) is wrong. But I cannot figure out where the bug is. You might want to check the actual shape of `x` at run time by replacing the line `nodes['dis_real'] = self.dis(x, y, True)` in `src/musegan/model.py` with the following code.
> 
> ```python
> print_op = tf.print(tf.shape(x))
> with tf.control_dependencies([print_op]):
>     nodes['dis_real'] = self.dis(x, y, True)
> ```
> 
> btw, I found an even bigger bug (though it won't cause errors) while rereading the code. 😅 Thanks anyway. 👍

I meet the same problem when I train with my own data, how can you fix this problem ?
thanks
